### ISSUE TITLE
VarDictJava 1.5.5: structural variant events reported with `--nosv`

### ISSUE THREAD

**Issue by chapmanb** [AstraZeneca-NGS/VarDictJava#143]
We're testing VarDict 1.5.5 for small SNP and indel calling with `--nosv` specified, but seeing structural variation events produced in the output. For example, when running:
```
vardict-java -G $REF -f 0.001 -N name -b in.bam -c 1 -S 2 -E 3 -g 4 --nosv -Q 10 -F 0x700 regions.bed | teststrandbias.R | var2vcf_valid.pl -A -N name -E -f 0.001  | bgzip -c > out.vcf.gz
```
there is a 1.1kb DUP structural variant in the output:
```
chr1    11144688        .       C       <DUP>   44      PASS    SAMPLE=PrCa-07-PROSTATE-N-1-IDTp7UMI27-GTAGTACC;TYPE=DUP;DP=1802;VD=2;AF=0.0011;BIAS=2:0;REFBIAS=980:822;VARBIAS=0:2;PMEAN=72;PSTD=1;QUAL=44.4;QSTD=1;SBF=0.20849;ODDRATIO=0;MQ=60;SN=4;HIAF=0.0011;ADJAF=0.0011;SHIFT3=70;MSI=1;MSILEN=1;NM=0.0;HICNT=2;HICOV=1804;LSEQ=TCTGGCGGATGATCTCTCGT;RSEQ=CCACTGTGCCCAGCCTGGGG;DUPRATE=0;SVTYPE=DUP;SVLEN=1100;SPLITREAD=2;SPANPAIR=0  GT:DP:VD:AD:AF:RD:ALD   0/1:1802:2:1802,2:0.0011:980,822:0,2
```
Since we're currently only expecting SNP and indel events in the output, this triggers downstream processing issues due to not correctly handling the differently represented SV events.

Is it possible to remove all SVs from the output and detection when `--nosv` is supplied? I'll send along a reproducible test case offline as well. Thanks so much.

**Comment by PolinaBevad** [comment]
@chapmanb, hello!
The PR with the fix for this issue is prepared here: https://github.com/AstraZeneca-NGS/VarDictJava/pull/145

Variants, that are determined as SV will be deleted from the output. We will look for the better solution to check it in place at local realignment step, but we need to make some refactoring before it, so this is a quick fix.

Test cases that you sent were added to our test case set. 
Thank you for reporting this!
Perl version will be updated too.

**Comment by PolinaBevad** [comment]
@chapmanb , hello!
I'll close the issue, the option deletes SVs found in local realignment, since 1.5.6 release.
