### ISSUE TITLE
is the single mode for germline and somatic calling? 

### ISSUE THREAD

**Issue by HeXY0515** [AstraZeneca-NGS/VarDictJava#172]
Hi,
Is VarDictJava single mode used for calling somatic variatns from tumor sample or germline vatiants from normal  sample or even the both somatic and germline?

**Comment by PolinaBevad** [comment]
@HeXY0515, hello!

If I understand your question correctly, the output in single mode will contain all the variants without determining their types. VarDict can classify the type of variant (germline, somatic etc.) only in paired mode, with both tumor and normal samples used. So you will get all of them in a single mode for the sample you use, but they will be not classified.
Is this what you wanted to clarify?

**Comment by HeXY0515** [comment]
Yes,  sorry for the vague express but I think you understood me. But to confirm,  I will get both somatic and germline  variants running in single mode  with a tumor sample, and I also will get both germline and somatic variants running in single mode with a  normal sample. So the question is how to classify the  somatic and germline variants in the results?

**Comment by PolinaBevad** [comment]
@HeXY0515, hello,

Well, I think it is a quite complicated task to determine the type of variant when you already have the results from the single mode. One way that I know, is to compare the results with databases like dbSNP, COSMIC, etc. You can exclude germline variants contained in dbSNP (common SNPs with population frequencies >1%) from results, but anyway, a lot of germline SNPs will be left nondetermined, because they are specific to the individual or family/subpopulation. It is some part of work that VarDict can't do.
VarDict can automatically determine the germline/somatic type **only** in somatic (paired mode) when tumor and normal samples are run together. It is a typical algorithm for many variant callers. 

I think if it is critical for you to use only one sample (for example, if the normal sample is absent), there are few other variant callers, that can work only on tumor sample (without normal) and determine somatic variants, examples:  https://genomemedicine.biomedcentral.com/articles/10.1186/s13073-017-0446-9 and https://academic.oup.com/bioinformatics/article/32/6/808/1744570  

If you have both samples (tumor-normal), it is better to re-run VarDict with them in the paired mode to obtain this information automatically. 
I hope my answer will help you.

**Comment by HeXY0515** [comment]
@PolinaBevad ,
Thank you very much and  it is clear enough !

**Comment by PolinaBevad** [comment]
@HeXY0515, great! Thank you for the question. I will close the issue, but you can re-open it if needed.
