### ISSUE TITLE
DRAGEN input alignment: NumberFormatException in MSI calculations

### ISSUE THREAD

**Issue by chapmanb** [AstraZeneca-NGS/VarDictJava#173]
Polina, Pablo, Zhongwu and all;
While running the latest release on DRAGEN input alignments, we're hitting an issue apparently in MSI calculations:
```
Exception in thread "main" java.lang.NumberFormatException: For input string: "?"
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
        at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
        at java.lang.Double.parseDouble(Double.java:538)
        at com.astrazeneca.vardict.Utils.roundHalfEven(Utils.java:102)
        at com.astrazeneca.vardict.modules.ToVarsBuilder.toVars(ToVarsBuilder.java:620)
        at com.astrazeneca.vardict.VarDict.somaticNotParallel(VarDict.java:439)
        at com.astrazeneca.vardict.VarDict.nonAmpVardict(VarDict.java:312)
        at com.astrazeneca.vardict.VarDict.start(VarDict.java:76)
        at com.astrazeneca.vardict.Main.main(Main.java:35)
```
I'm not sure how we're getting this incorrect from reading the code, so could use a pointer on what is going wrong.

Here is a small self contained test case which replicates the issue in the latest 1.5.8 release:

https://s3.amazonaws.com/chapmanb/testcases/vardict_dragen.tar.gz

Thanks much for the help and please let me know if I can provide any other details.

**Comment by PolinaBevad** [comment]
@chapmanb , hello!
Thank you a lot for finding this bug!

It needs to be fixed in both Perl and Java version. In Perl it causes "Illegal division by zero". 
The error appears while calculating msi for deletions: the cigar on read `A00130:81:HFFWLDSXX:2:1663:14009:22060` in normal.bam after modifying it through the realigner becomes `8S74M0D69M` and the variant description string is collected as deletion `-0` for this cigar.

I will add a fix to modify cigar algorithm in this part: 
https://github.com/AstraZeneca-NGS/VarDictJava/blob/master/src/main/java/com/astrazeneca/vardict/modules/CigarUtils.java#L315. It will create the cigar string without `D` if the deletion part becomes zero after modifying, so the final cigar will be `8S74M69M`. @pcingola, @zhongwulai, what do you think about this change?

**Comment by zhongwulai** [comment]
Hi @PolinaBevad, this is the aligner's problem, where a perfect match becomes 1 insertion and two deletions.  Dragen is new to VarDict, and thanks for pointing this out.  I fixed it in Perl version, where I added line 1011 to remove 0D in the final CIGAR and combine the two matches.  @PolinaBevad, as you already pointed out, you probably need to change line 315 in CigarUtils.java.

**Comment by ohofmann** [comment]
Dear all - any chance of a release? I'd love to test the DRAGEN alignments to see what other surprises they hold.

**Comment by PolinaBevad** [comment]
@ohofmann, hello!
Fixes for this case are ready and we will release soon. In my opinion, this may happen next week.
We will wait for your results after release to find out if there are other problems with DRAGEN!

**Comment by ohofmann** [comment]
Thanks for the update!

**Comment by PolinaBevad** [comment]
Brad, hello!
I will close this issue because the fix is already merged. It will be included in future release.
Thank you a lot for the test case!
