### ISSUE TITLE
should I clip off the primer sequences before using VarDictJava with amplicon mode?

### ISSUE THREAD

**Issue by FrankFeng** [AstraZeneca-NGS/VarDictJava#191]
Should I remove or clip off the primer sequences, or just leave them in the BAM files, before using VarDictJava with amplicon mode? Which one will deliver better results? I have a script which can be used to clip off the primer sequences in a BAM file, but I am not sure if I should use it for variant calling with VarDictJava. Thanks!

**Comment by PolinaBevad** [comment]
Frank, hello!

It is better to delete such sequences from the BAM files because they can be used in the local realignment of VarDict. 
We also added functionality for skipping such sequences with option `--adaptor` to VarDictJava, but it is not released in current version (will be released in 1.6.0). You can try it if you want, but you will need to build new version as described here: https://github.com/AstraZeneca-NGS/VarDictJava#compiling

**Comment by FrankFeng** [comment]
Thanks Polina!
