### ISSUE TITLE
Empty vcffile after var2vcf_valid.pl

### ISSUE THREAD

**Issue by ALFLAG** [AstraZeneca-NGS/VarDictJava#200]
Hello everyone,
I describe the problem over there : https://github.com/AstraZeneca-NGS/VarDict/issues/63
because it is identical.

If anyone can help us.
Thank You.

Alexandre

**Comment by PolinaBevad** [comment]
Alexandre, hello!

I looked at the issue and files you attached and found the cause of this behavior. 
The names of chromosomes that you use are incorrectly recognized because of this line in var2vcf_valid.pl: `next if ( $c =~ /X/ || $c =~ /Y/ );` 
https://github.com/AstraZeneca-NGS/VarDict/blob/master/var2vcf_valid.pl#L242 
Chromosome name in your file is `consensus_from_reference_KY933089` so it contains `Y` and such lines are skipped. 

We will fix it in new version but you can now fix it in your local copy of the script by replacing this line with:
`next if ($c eq "X" || $c eq "chrX" || $c eq "Y" ||  $c eq "chrY" );`
Please try it and let me know if something goes wrong.

**Comment by ALFLAG** [comment]
Polina, thank you so much.
I spend the last day trying to understand this problem, but I'm not familiar with Perl language.
Your solution worked perfectly, thanks a lot.

Have a good day!

Alexandre
