### ISSUE TITLE
./gradlew clean installDist without download of gradle zip

### ISSUE THREAD

**Issue by jwhite007** [AstraZeneca-NGS/VarDictJava#202]
Our Linux servers are behind a firewall which prevents download of https://services.gradle.org/distributions/gradle-4.10.2-bin.zip. I've downloaded that file via other means and have placed it in VarDictJava/. I'd like to be able to run ```./gradlew clean installDist``` without triggering the download. This also goes for other files that might need to be downloaded during the installation. Is there a download cache or temp dir that is being used and watched for previously downloaded files? Thanks.

**Comment by PolinaBevad** [comment]
James, hello!
Gradle caching has a lot of limitations (due to https://github.com/gradle/gradle/issues/1338) so we don't use it. I think it is better to build VarDictJava with `./gradlew clean installDist` once in the environment without firewall and then distribute only `build\install\VarDict\` folder to your Linux servers. Is this possible for you?

**Comment by jwhite007** [comment]
@PolinaBevad, I did what you suggested, and everything seems to be working so far. Thanks.
