### ISSUE TITLE
A heterozygotic SNV with ref allele depth is 0

### ISSUE THREAD

**Issue by Gerde89** [AstraZeneca-NGS/VarDictJava#219]
Hi,
VarDict give a strange result that a heterozygotic SNV (GT is '1/0') with ref allele depth is 0:
`2       215632256       .       A       G       721     PASS    ADJAF=0.002;AF=0.5274;BIAS=0:2;DP=493;DUPRATE=0;HIAF=1.0000;HICNT=260;HICOV=260;LSEQ=AACAGCTTGACTATATCCAC;MQ=60;MSI=1;MSILEN=1;NM=1.1;ODDRATIO=0;PMEAN=26.9;PSTD=1;QSTD=1;QUAL=89.9;REFBIAS=0:0;RSEQ=TGCCCATTCTTGGCTGCATC;SAMPLE=YF_1;SBF=1;SHIFT3=0;SN=520;SPANPAIR=0;SPLITREAD=0;TYPE=SNV;VARBIAS=137:123;VD=260   GT:DP:VD:AD:AF:RD:ALD   1/0:493:260:0,260:0.5274:0,0:137,123`

The command:
`VarDict -G hg19.fa -N sample_name -f 0.001 -b my.bam -z -c 1 -S 2 -E 3 -g 4 -th 4 region.bed | teststrandbias.R | var2vcf_valid.pl -N sample_name -E -f 0.001 | awk '{if ($1 ~ /^#/) print; else if ($4 != $5) print}' >out.vcf`

I found a complex variant be called  1bp upstream of this position, could it be the reason?
`2       215632255       .       CA      TG      710     PASS    ADJAF=0.0101;AF=0.4789;BIAS=2:2;DP=497;DUPRATE=0;HIAF=0.4789;HICNT=238;HICOV=497;LSEQ=TAACAGCTTGACTATATCCA;MQ=60;MSI=2;MSILEN=2;NM=1.4;ODDRATIO=1.22838050314465;PMEAN=28;PSTD=1;QSTD=1;QUAL=90;REFBIAS=137:122;RSEQ=TGCCCATTCTTGGCTGCATC;SAMPLE=YF_1;SBF=0.27878;SHIFT3=0;SN=476;SPANPAIR=0;SPLITREAD=0;TYPE=Complex;VARBIAS=138:100;VD=238 GT:DP:VD:AD:AF:RD:ALD   0/1:497:238:259,238:0.4789:137,122:138,100`

Here is the BAM:
[bamfiles.zip](https://github.com/AstraZeneca-NGS/VarDictJava/files/3097510/bamfiles.zip)

Best,
Gerde

**Comment by PolinaBevad** [comment]
Gerde, hello!
I suppose ref allele depth here must be 0 because in IGV I see only G bases on position 215632256 and no ref bases in the reads. The VD is less than DP here because there are a lot of hardclips on this position (about half of the reads) and they are skipped by VarDict and so they are not included in VD. 
In a complex variant on 215632255 ref bases exist so they are counted to REFBIAS and ref depth (even they are hard clips).
Please let me know If you have some objections about this behavior of VarDict.

**Comment by Gerde89** [comment]
@PolinaBevad Hi, Polina,

Thanks for explaining.
I' m still confused about the complex variant, since there are no reads support ref allele (CA) in postion 215632255 to 215632256, how the ref allele depth in AD & RD calculated ?
Actually, reads are hard-clip to avoid double count on overlapped region of Read1 and Read2 before VarDict, but I could not see any hard-clip on position 215632256, am I misunderstanding ? And, I could not understand why hard-clip reads should be skipped, forgive my ignorance.

Best,
Gerde

**Comment by PolinaBevad** [comment]
Gerde, hello!

We don't skip the whole reads that contain hard-clips, but only hard-clip bases, because we can't get information about the sequence from them for further analysis.
But I carefully looked at this situation, hard clips ended before these variants and it seems that we have another case here. 

The coverage for SNV A->G variant is gathered only from reads where we don't have complex CA->TG variant, so we have CA->TG variant in 238 reads, and SNV will be in other 260 reads. Ref allele depth for this MNV includes reads, where even one base in bases covered variant is the same as in reference, so it won't be zero, but SNV doesn't have ref bases at all, so it will be zero. That the logic that we use and that's why you have such values for ref depth in these variants.

**Comment by Gerde89** [comment]
@PolinaBevad  Hi, Polina,

As we could not see any reads support ref allele (A) in pos 215632256, I think the ref allele depth of the complex variant and the genotype of pos 215632256 are inaccurate.
Maybe we should treat both positions as SNV for this situation ? What's your opinion ?
Thanks a lot !

Best,
Gerde

**Comment by PolinaBevad** [comment]
Gerde, hello!
We need a little time to discuss this case and decide whether this is an issue or not and whether we should recognize them as two separate SNVs or not. I'll let you know about the result.
Thank you!

**Comment by PolinaBevad** [comment]
Gerde, hello,
Zhongwu Lai (the creator of VarDict and the person who makes the final decision on such matters) looked at this issue and he thinks that we still have to treat these variants as MNV CA->TG and SNV A->G, and the depths for REF bases should stay the same. Sorry, but we will not change the calculation of the depths. Can I close the issue or do you have any comments on this?

**Comment by Gerde89** [comment]
@PolinaBevad  Yeah, thanks a lot ! I would close the issue.
