### ISSUE TITLE
P-value floating point precision problem in paired sample analysis

### ISSUE THREAD

**Issue by thkitapci** [AstraZeneca-NGS/VarDictJava#223]
Hi,
Vardict includes at most 6 decimals. This is a problem when there are a lot of variants because any p-value smaller than 10^-6 is rounded down to zero. This makes it impossible to do any multiple testing correction because all those p-values "rounded down to zero" are getting detected as significant by definition. Normally having an exact p-value = 0 is almost impossible  
but since here an exact fisher-test is performed it might be possible to get p-value=0. Still there is need for much higher decimal precision to make sure these zeros are real zeros and not just p-values<=10^-6 that are rounded down to zero.  

How can I increase the decimal precision when running vardict so that more decimal points are written in the VCF output ?  

As an example here is my VCF file 
https://drive.google.com/file/d/1dssDEVJ4AFwYcAmhOw6XEGKMCM3Xb1jf/view?usp=sharing

I extracted all p-values from variants that passes the filtering

`cat myPaired_exp1_vs_control.vcf |awk '{if ($7=="PASS") {split($8,a,";");split(a[10],b,"="); if (b[2]<=1) print b[2]}}' >all_p_values.txt
`
Then I take all these p-values and apply BH multiple testing correction in R. I found 5586 significant p-values at FDR 5% level. 

This is the number of p-values exactly equal to zero 

`cat myPaired_exp1_vs_control.vcf |awk '{if ($7=="PASS") {split($8,a,";");split(a[10],b,"="); if (b[2]==0) print b[2]}}' |wc -l
`

Hamdi

**Comment by PolinaBevad** [comment]
Hamdi, hello,

If you want to increase p-value and oddratio fields precision, then you have to change testsomatic.R file:
https://github.com/AstraZeneca-NGS/VarDict/blob/2a0fda38b280d3e9624ca02b87c681658f96467a/testsomatic.R
in lines 31, 32, 34, 35, 46 and 47 to the needed precision, like:
`pvalues1[i] <- round(h$p.value, `**6**`)`
It will round values to the 6th number of decimal places, i.e.10E-6.

After that the second step must be rerun with fixed R script because when values are already rounded we will not be able to get the necessary information from them.
Please try it and let me know if you will have other questions!

**Comment by thkitapci** [comment]
Hi @PolinaBevad ,
I modified testsomatic.R and removed all the "round" functions. Is there any need to do this rounding ? Should I keep the "round" function and set the parameter to a very high value or can I simply remove the "round" function to include as many digits as possible ? If I remove the round function will there be a "default" rounding or will it output the max possible digits in the output ? It takes about 7 hours to run the R and Perl scripts I can share my results when I get them later today. 

Thanks
Best Regards
Hamdi

**Comment by PolinaBevad** [comment]
Hamdi, hello,
Yes, if you will delete round function values for SBF and ODDRATIO must be written in VCF without round (double precision, I guess). But you still have to save a value in pvalues and oddratio arrays, so your lines will be like:
`pvalues1[i] <- h$p.value`
Let me know if something is not clear!

**Comment by PolinaBevad** [comment]
Hamdi, hello!
I guess you got the needed result so the issue can be closed. Thank you!

**Comment by thkitapci** [comment]
Hi @PolinaBevad,
I removed the round function and stores p values and odd rations without any rounding. The code seems to work fine but I am getting some unusually low P-value here is a manhattan plot and a qqplot of the SSF (p-value) I got in my paired sample analysis. It seems there is a huge p-value inflation. Can you explain why this might be happening ? Can this be a technical artifact due to floating point arithmetic or something else ? Below are my plots (generated with R qqman package) Red line indicates the bonferroni corrected p-value threshold. y-axis is -log10(p-value)

![image](https://user-images.githubusercontent.com/16551331/57951354-9f0b6200-789e-11e9-9cf2-daa7c5473dc7.png)

![image](https://user-images.githubusercontent.com/16551331/57951374-b77b7c80-789e-11e9-8194-c45a13df3e19.png)

**Comment by PolinaBevad** [comment]
Hamdi, hello!

Sorry, I'm not a specialist in statistics, but I think that you get such QQ plot because such precision is not used in typical normal QQ plots. Most of them combine all p-values less than 0.001 or smaller limit (threshold is based on the area of the study) to one group. If you will try to do something like this (i.e your y-axis will also have the same limit as x-axis: -log10(p-value)=6), perhaps you will have the diagonal line in QQ plot which will be closer to the normal distribution. 

Here is an article about the significance of small p-values: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2742983/ and the discussion at: https://stats.stackexchange.com/questions/78839/how-should-tiny-p-values-be-reported-and-why-does-r-put-a-minimum-on-2-22e-1, maybe they also will be helpful. The second one has an answer about computational problems in floating arithmetic (and description of epsilon error). In a nutshell, it doesn't matter if the p-value is 10^-17 or 10^-308, such values can be considered as a value below the threshold. 
I hope this helps you.

**Comment by thkitapci** [comment]
Hi @PolinaBevad ,
I will read the links you provided and think about this again. Regardless of the "extra small p-values" The fact that there are so many significant p-values below the bonferroni corrected threshold ("red line in the first picture) is unusual. Either there is a huge false positive rate or some technical artifact that is inflating the p-values here. 

Thanks
Hamdi
