### ISSUE TITLE
gVCF option

### ISSUE THREAD

**Issue by thkitapci** [AstraZeneca-NGS/VarDictJava#227]
Hi,
Does VarDict have the option to generate a gVCF (genomic VCF) rather than a regular VCF ?

Otherwise can you suggest a way to convert the VCF generated by VarDict to gVCF using an external tool ?

Thanks
Best Regards
Hamdi

**Comment by clintval** [comment]
Hi @thkitapci, VarDictJava _almost_ outputs properly formatted gVCF!

Having VarDictJava produce valid gVCF is something that I have been working on with these PRs and I will continue to patch as I have issues:

- https://github.com/AstraZeneca-NGS/VarDict/pull/58
- https://github.com/AstraZeneca-NGS/VarDict/pull/94

In an example VarDictJava command, if you simply remove the `awk` filter for homref calls, you will produce a gVCF (@PolinaBevad is this still true?):

```patch
--- 1.sh	2019-05-17 10:11:03.000000000 -0700
+++ 2.sh	2019-05-17 10:11:12.000000000 -0700
@@ -1,5 +1,4 @@
 VarDictJava/build/install/VarDict/bin/VarDict -G /path/to/hg19.fa -f 0.001 -N sample_name -b /path/to/sample.bam  -z -R chr7:55270300-55270348:EGFR \
-    | awk '{if ($6 != $7) print}' \
     | VarDictJava/VarDict/teststrandbias.R \
     | VarDictJava/VarDict/var2vcf_valid.pl -N sample_name -E -f 0.001 \
     > vars.genome.vcf
```

Sadly, I have not tested the latest versions of VarDictJava to see if the resulting gVCF are still valid VCF (against the v4.2 specification) but it is something I would love to see worked on! Do let me know what you encounter!

The best way that I have found to validate that a VCF is is valid, is with the tool `vcf-validator`: https://github.com/EBIvariation/vcf-validator

**Comment by thkitapci** [comment]
Hi @clintval 
Thanks for your reply. Can you please clarify where is this "awk" command that I can remove to produce a gVCF ? Here is the command I run for my VarDict 

`VarDict -th 4 -G $reference_fasta -f $AF_THR -N $sample_name -b $bam_file -z -c 1 -S 2 -E 3 -g 4 $bed_file 2>$sample_name.vardictError | teststrandbias.R 2>$sample_name.RError | var2vcf_valid.pl -N $sample_name -E -f $AF_THR 2>$sample_name.vcfError >$sample_name.vcf`

I don't have an "awk" command here and I have never seen and the awk command you mention in the pipeline. Is it possible that this awk was moved to somewhere else (maybe it is embedded in the java code ?) 

Thanks
Hamdi

**Comment by clintval** [comment]
I'll wait for @PolinaBevad to chime in. I think I'm living in the past!

**Comment by PolinaBevad** [comment]
Hamdi, hello!
@clintval, thank you for participating in the issue! 

Yes, VarDict can generate gVCF which will contains all variant and non-variant sites, but it must be started with `-p` option at the VarDict step. 
In this case all non-variants sites also will be in output file and no filtering will be applied at the VarDict step. Filters will be applied only in step of var2vcf_valid.pl script. awk line can be omitted of course, because you have to get results when REF and ALT are equal. Non-variants lines have TYPE="REF", VD=0 and ALT="." in output VCF and then you can filter them by DP field also.
Non-variant looks like:
`chr1	1275920	.	A	.	0	f0.02	SAMPLE=abc;TYPE=REF;DP=23;END=1275920;VD=0;AF=0;BIAS=2:0;REFBIAS=7:16;VARBIAS=0:0;PMEAN=22.7;PSTD=1;QUAL=36.2;QSTD=1;SBF=1;ODDRATIO=0;MQ=60;SN=22;HIAF=1.0000;ADJAF=0;SHIFT3=0;MSI=0;MSILEN=0;NM=0.1;HICNT=22;HICOV=22;LSEQ=0;RSEQ=0;DUPRATE=0;SPLITREAD=0;SPANPAIR=0	GT:DP:VD:AD:AF:RD:ALD	0/0:23:0:23,0:0:7,16:0,0`
Variant:
`chr1	1275921	.	C	A	0	v2;pSTD;q22.5;SN1.5	SAMPLE=abc;TYPE=SNV;DP=22;END=1275921;VD=1;AF=0.0455;BIAS=2:0;REFBIAS=6:15;VARBIAS=0:1;PMEAN=43;PSTD=0;QUAL=12;QSTD=0;SBF=1;ODDRATIO=0;MQ=60;SN=0;HIAF=0;ADJAF=0;SHIFT3=0;MSI=1;MSILEN=1;NM=1.0;HICNT=0;HICOV=16;LSEQ=GAGCTCAGAGGAGCTGGAGA;RSEQ=ATGGGTAGGGGGGTGGGAAC;DUPRATE=0;SPLITREAD=0;SPANPAIR=0	GT:DP:VD:AD:AF:RD:ALD	0/1:22:1:21,1:0.0455:6,15:0,1`

We fixed type "REF" in one of the previous PRs (https://github.com/AstraZeneca-NGS/VarDict/pull/103), so may be you have to update your version of .pl scripts from VarDict repo (https://github.com/AstraZeneca-NGS/VarDict). In old versions TYPE field for non-variant was empty.

I'm not sure if you will use it in WGS or not, but I want to warn that producing of gVCF with `-p` option can be very time consuming because all the positions must be written in output and then processed in R script. If you will use it in WGS maybe it is better to run it on each chromosome (by splitting BED file) separately and then merge the resulted gVCFs in one. We didn't test `-p` option in WGS, but I checked it on some exome runs and it worked fine.
Please, try it and let me know if there are any problems!

**Comment by thkitapci** [comment]
Hi @PolinaBevad,
I am running my analysis on transcriptome which should be similar size to exome. The output of the vardict is about 55GB with the -p option (it was ~350MB without the -p option) The problem I am having right now is with the teststrandbias.R I am getting the following error when running the R script

Error: Incorrect input detected in teststrandbias.R
Execution halted

Here is are my commands
```
VarDict -p -th 4 -G $reference_fasta -f $AF_THR -N $sample_name -b $bam_file -z -c 1 -S 2 -E 3 -g 4 $bed_file 2>$sample_name.vardictError >$sample_name.vardictOut
cat $sample_name.vardictOut|teststrandbias.R 2>$sample_name.RError >$sample_name.ROut
cat $sample_name.ROut| var2vcf_valid.pl -N $sample_name -E -f $AF_THR 2>$sample_name.vcfError >$sample_name.vcf

```
I can upload my input files for debugging if it helps

Hamdi

**Comment by PolinaBevad** [comment]
Hamdi, hello,

This looks like the version of teststrandbias.R is also old. Please, could you try to use these versions of files from VarDict repository (you have to do it manually because they are not released as part of Java yet):
https://github.com/AstraZeneca-NGS/VarDict/blob/master/teststrandbias.R
https://github.com/AstraZeneca-NGS/VarDict/blob/master/var2vcf_valid.pl
This error was before fixes because of empty field in type in non-variant lines.
Let me know if you will have any other errors.

**Comment by thkitapci** [comment]
Thanks for the quick response. I will download these 2 files and replace with the existing ones and run again now to see if it fixes the problem

Hamdi

**Comment by thkitapci** [comment]
Hi @PolinaBevad,
I re-run my samples with the same command after changing the R and perl script to the ones you mentioned in your comment this time I am getting this error

```
VarDictJava/build/install/VarDict/bin/teststrandbias.R: line 7: syntax error near unexpected token `newline'
VarDictJava/build/install/VarDict/bin/teststrandbias.R: line 7: `<!DOCTYPE html>'

```

Any idea why I am getting this error ?

**Comment by thkitapci** [comment]
Hi @PolinaBevad,
I am having memory problem with the testsrandbias.R because this code keeps the entire dataset in the memory it fails even with 192GB of memory when loading a vardict output generated with -p option (~55GB input file) 

How much memory did you use in your exome run test ? 

What was the input size when you run vardict with -p option on a exome dataset ? 

Also I have written a replacement for the 

https://github.com/AstraZeneca-NGS/VarDict/blob/master/teststrandbias.R 

I don't think there is a need to keep the entire input in the memory here is my solution (I did some small tests and it seems to work but it should be tested to make sure it works fine)

https://gist.github.com/thkitapci/beee80a06a609112e886c4bb5aff830e

This code is written in python and read the input from stdin line by line without storing the input in the memory so it requires very small amount of memory to run. 

Then uses the same R fisher.exact function through rpy2 package and writes the output in the same format used in teststrandbias.R

What do you think about this solution ? I can do some testing and add the pre-condition tests to this code and maybe it can be included in the vardict repository if you think it is useful. 

Hamdi

**Comment by PolinaBevad** [comment]
Hamdi, hello,
The exome I tested was from a 10Gb raw output, and 32Gb RAM was enough in that test. The `textConnection` that we are using in .R script to avoid temp files can be very time and memory consuming. But we hold raw file in the memory because the next `var2vcf_valid.pl` script must retrieve the complete data at least about one chromosome to process (it gather information about chromosomes, samples and already seen variants from the whole file). 
So `var2vcf_valid.pl` will also hold in memory the whole file, and in this case, when you have 55 Gb input, I guess it is better to: 
1. Split raw input by chromosomes into separate files (with `awk {print > $2".var"}` it is simple) .
2. Process these files with R script (or your python code) and save the intermediate results to files.
3. Process each file with var2vcf_valid.pl.
4. Use `vcf-concat` to combine VCFs. 
These 2 and 3 steps also can be run in multiple threads with GNU parallel, for example. GNU parallel can run a simple script for each of the input files, and that what is needed here.
If you will use python code you have to separate runs of fisher test and var2vcf_valid.pl anyway just to be sure you have the complete output from fisher test step. So you couldn't just redirect output from your python code with Fisher test by `>`, but first, you need to save it to the file and then start .pl script. In another case .pl script can start running without the whole data to process.
Let me know if there is something that has to be discussed deeper.

**Comment by PolinaBevad** [comment]
Hamdi, hello,
Maybe it will be helpful, here are 2 scripts for splitting and running R and pl scripts by steps that I described:
https://drive.google.com/open?id=17xznjYwbNouTZg8CURwj_RMlkd6KrDKD 
You can change them for your needs. It also runs GNU parallel (can be installed from packages).

**Comment by thkitapci** [comment]
Hi @PolinaBevad,
Thanks for the clarification. I will try to split the files by chromosome and run it again. One problem is the number of lines in my VarDict I have 357.483.077 lines in the output file. I think I should apply a total depth filtering (column $8) before the R / Perl steps. I think I will look at the distribution of total depth in one of my files to decide on a filtering criteria, do you guys have a filtering suggestion for total depth before running the R / Perl scripts?

Thanks
Hamdi

**Comment by PolinaBevad** [comment]
Hamdi, hello,
We typically filter lines with DP<3 for single sample, but of course the limit can be higher, based on your coverage in BAM. I think you can also use this value first to try to reduce the number of lines.

**Comment by thkitapci** [comment]
Thanks for the suggestion. I am looking to VarDict options and I can't see any argument to filter for DP is there a build in argument to filter for DP in the java code or do I need to perform the filtering after the file is generated (or by piping (|) the output to awk) ?

Hamdi

**Comment by PolinaBevad** [comment]
Hamdi, we don't have filtering by DP in VarDict, but this filter is in var2vcf_valid.pl script here: https://github.com/AstraZeneca-NGS/VarDict/blob/master/var2vcf_valid.pl#L148
These filters are not "hard" by default (i.e. they add filter name to FILTER field in VCF and don't remove the variant), but because of huge number of lines you can first remove such lines before Fisher test (yes, by awk, for example).

**Comment by thkitapci** [comment]
Thanks @PolinaBevad,
I will do a filtering at the beginning but I am also realizing that my VarDict output is too big for a transcriptome


This is the VarDict command I am running

VarDict -p -th 4 -G $reference_fasta -f $AF_THR -N $sample_name -b $bam_file -z -c 1 -S 2 -E 3 -g 4 $bed_file 2>$sample_name.vardictError >$sample_name.vardictOut

I sum the size of all entries in my BED file it is longer than the reference genome. I guess this is due to overlapping positions.

Here are my files and the counting I did

My organism is Mus musculus (mm10) and my data is RNA-seq data, I am trying run VarDict on the entire transcriptome

Bed file:
https://drive.google.com/file/d/1LjtD7GW3Z9KCQtQVZP6iG-8OEKU-3wwC/view?usp=sharing

Count the total size of the all region in the BED file

cat gencode.vM19.annotation.gtf.bed |awk 'BEGIN{c=0}{c+=($3-$2)}END{print c}'

This result in a total size of 5.612.666.107

Since BED file contains overlapping fields (such as gene and every exon / intron of those genes) then I counted just the fields called "gene"

cat gencode.vM19.annotation.gtf.bed | awk 'BEGIN{c=0}{if($8=="gene") c+=($3-$2)}END{print c}' 
Which result in 1.298.299.843 which is still too large for the transcriptome

Here is my fasta file
https://drive.google.com/file/d/1aXH4eSpAP8dVoIiLuVhDKvqD0aQhYRTd/view?usp=sharing

cat mm10.fa |grep -v ">" |wc -c

This result a total nucleotide count of 2.759.606.900

Does VarDict do any filtering on the BED file to disregard overlapping positions or do I need to filter the BED file to make sure to remove any overlapping positions ? If I need to filter the BED file can you help me how to filter to get the entire transcriptome without overlapping nucleotides ?

**Comment by FrankFeng** [comment]
Hi @PolinaBevad ,

Is 'awk '{if ($6 != $7) print}'' necessary, if I only want variants and I don't use the `-p` option at the VarDict step?

Thanks!

**Comment by PolinaBevad** [comment]
@FrankFeng, hello!
No, it is not necessary to use this `awk` line, because from at least 1.5.2 version non-variant lines (with REF==ALT) mustn't appear in the output in the simple mode without pileup. We had some cases in somatic mode when such non-variants appeared (it was a bug), but it was fixed in master (here https://github.com/AstraZeneca-NGS/VarDictJava/commit/95cd8bc41ff59f15677a29e6f44b4bbb485d81d8).

**Comment by PolinaBevad** [comment]
Hamdi, hello!

VarDict makes filtering on overlapping regions in the step of var2vcf_valid.pl. 
It saves seen variants (this line: https://github.com/AstraZeneca-NGS/VarDict/blob/master/var2vcf_valid.pl#L137) and skips if they already met. 

But I looked at the BED file you provided and actually, I think that you do not need to process stop codons, for example. Each of this line will be processed by VarDict separately, so the raw output will be at least 3x times bigger than needed (you have at least gene+transcript+exon lines for each exon). 

Perhaps you can delete "exon", "transcript" etc. lines and leave only "gene" lines. Or I guess a better way is to download a new one BED file from UCSC for canonical transcripts or exons (based on your needs) as described here: https://www.biostars.org/p/93011/#93206 and use it. By using reduced BED file you will decrease the time of processing for all steps of VarDict and the size of the raw output. In my opinion, you can use canonical transcript BED, it will have some overlapping regions, but not a critical amount of them, so you can leave them without changes.

**Comment by PolinaBevad** [comment]
Hamdi, hello!

Did you manage to get the gVCF file after using the new BED file? Is there anything else I can help with?

**Comment by PolinaBevad** [comment]
Hamdi, hello,
I will close the issue because I hope that you got gVCF file. If you have any other questions, please let me know!
