### ISSUE TITLE
generate a bed for WGS data

### ISSUE THREAD

**Issue by JunyanZH6** [AstraZeneca-NGS/VarDictJava#232]
Hi,
I want to call variants on WGS data using VarDict. I need a bed file for reference genome hg38.
I found a bed file for reference genome hg19 from https://github.com/AstraZeneca-NGS/VarDict/blob/2a0fda38b280d3e9624ca02b87c681658f96467a/hg19_5k_150bpOL_seg.txt.gz
In this bed file, 11bp is skipped from both start and end position of each chromosome. 
Is there some special reasons to skip 11 bp? And should I follow its window size and overlapping size?
 Is some scripts available for generating bed file for whole genome?
Thanks a lot.

**Comment by PolinaBevad** [comment]
Junyan, hello!

I really don't know why 11 bp were skipped here, but I think it is not significant, because there are N's at these places in the reference. The overlapping size that we recommend is 150 bp and here you can find some information about the windows size and overlapping: https://github.com/AstraZeneca-NGS/VarDictJava/wiki/Best-practics-for-WGS-and-multithreading 

I guess you can generate the BED file with `bedtools`.
You have to use the genome file for hg38 (it must be in the `genomes/` of bedtools folder). For example, this will create regions with a length of 50150 bp, 150 bp in each window will overlap with the next:
`bedtools makewindows -g human.hg38.genome -w 50150 -s 50000 > hg38.wgs.bed`

**Comment by PolinaBevad** [comment]
Junyan, hello!

I think this issue can be closed. I've updated wiki article about WGS with the description of BED creation.
