### ISSUE TITLE
error

### ISSUE THREAD

**Issue by lvran1234** [AstraZeneca-NGS/VarDictJava#237]
### Hello ,I am sorry to bother you,but I have error  when I use this new VarDict.

when I install VarDict
 ./gradlew clean installDist
BUILD SUCCESSFUL in 5s
5 actionable tasks: 4 executed, 1 up-to-date

 ./gradlew clean javadoc
BUILD SUCCESSFUL in 5s
3 actionable tasks: 3 executed

./gradlew distZip
BUILD SUCCESSFUL in 1s
4 actionable tasks: 3 executed, 1 up-to-date

but when I use it ,it have error : **Error: Could not find or load main class com.astrazeneca.vardict.Main**

Looking forward to your reply, thank you!

**Comment by PolinaBevad** [comment]
@lvran1234, hello,
I guess it appears because you used `clean` with `javadoc`. It is described here: https://github.com/AstraZeneca-NGS/VarDictJava#compiling

If you want to leave the compiled files, you have to run javadoc without `clean`. So re-build the project with commands:
`./gradlew clean installDist` 
`./gradlew javadoc`
`./gradlew distZip`
Please try and let me know if there are any problems.

**Comment by lvran1234** [comment]
Thank you so much. I have download a compiled one from git, and it works very well.

**Comment by PolinaBevad** [comment]
Thank you for reply! I will close the issue then.
