### ISSUE TITLE
Problem running within Conda environment

### ISSUE THREAD

**Issue by asgerjakobsen** [AstraZeneca-NGS/VarDictJava#238]
I am running VardictJava 1.6.0 in a conda environment as part of a pipeline. I installed VardictJava from bioconda. However, when I try running the command I get the following error:: 
`$ vardict-java`
`expr: error while loading shared libraries: libgmp.so.10: cannot open shared object file: No such file or directory
expr: error while loading shared libraries: libgmp.so.10: cannot open shared object file: No such file or directory
Error: Could not find or load main class com.astrazeneca.vardict.Main
`
The same error occurs if I type the full path to the symlink in the `conda_env/bin/` directory.

However, if I use the full path to the start up script it runs fine:
`$ conda_env/share/vardict-java-1.6.0-0/bin/vardict-java`

Do you have any ideas on how to solve this? I've attached my environment .yml file.
[tumour_only_env_vardictjava.txt](https://github.com/AstraZeneca-NGS/VarDictJava/files/3358595/tumour_only_env_vardictjava.txt)

**Comment by PolinaBevad** [comment]
Hi Asger,
I tried to install vardict-java via bioconda in a clean environment and didn't have any errors after installation: command `vardict-java` shows help message as it must. 

I think there are can be some problems with conda installation (perhaps lack of rights?), because of this `libgmp.so.10` error. I have encountered similar problems in other products while installing them in conda and I fixed them with symlinks directly to these libraries (I found them in other places than in conda configs) and also I have to add LD_LIBRARY_PATH to the folder with libraries.

But I think you can also try to get around this problem by adding vardict-java folder to PATH, like this:
`echo "export PATH=$PATH:full_path_to_bin_folder_of_vardict-java" >> ~/.bashrc` 
`source ~/.bashrc`

**Comment by asgerjakobsen** [comment]
Hi Polina,
Many thanks for your quick reply. Yes, that may be right. I couldn't locate the `libgmp.so.10` libraries but I suppose they must be there somewhere, otherwise it wouldn't ever work. It is strange because when I create a new environment with only vardict-java (and none of the other packages) the `vardict-java` command works.
Adding the adding vardict-java folder to the PATH also works - thanks for that suggestion.

**Comment by PolinaBevad** [comment]
Hi Asger,
Great, I'm glad it helped!
I'll close this issue, but please create another one if you will have other questions!
