### ISSUE TITLE
A problem about strand bias

### ISSUE THREAD

**Issue by lvran1234** [AstraZeneca-NGS/VarDictJava#239]
Hello，I  use Vardictjava for my data .
I found when R1 and R2 have long overlap ,and there is a mutation in the overlap ,the mutation will be judged reverse strand. When my insert fragment most shorter than 150bp ,then most mutation will be judged reverse strand. And there will make strand bias in data analysis  level, then I can't know which is real strand bias mutation come  from experimental .

So I want know  whether you have solution about it.

Looking forward to your reply, thank you!

**Comment by PolinaBevad** [comment]
@lvran1234, hello!

Could you please share the part of BAM file to illustrate this problem? And maybe you can attach screenshot from IGV with such mutation?
We also have an option `-UN` to skip one read if R1 and R2 overlap, perhaps it will be helpful in your case.

And did you successfully built 1.6.0 version (I mean issue #237)?

**Comment by lvran1234** [comment]
The strand bias problem appear in version  1.5.1 .I test version 1.6.0,there is no that problem ,but I have anthor question.
when R1 and R2 have long overlap ,and there is a mutation in the overlap ,the mutation will be calculated  twice? And the Depth will be calculated  twice too?
Thank you for your attention and reply !

**Comment by PolinaBevad** [comment]
Mutation coverage and depth will be calculated twice and exactly to get around this case we added `-u` and `-UN` options (you can look for the description in Readme.md). They aren't enabled by default because in some cases (small coverage of the region, for example) they can lead to missed variants. 

Basically, to avoid the doubling of depth both of the options will skip read if overlapping exists, but `-u` skips reverse read and `-UN` skips R2 read. So you can try one of these options if you need.

Also, you can look through the issue #60 and related ones about this problem.

**Comment by PolinaBevad** [comment]
@lvran1234, hello!

There are no new questions about the strand bias, so I will close the issue. If other questions appear, please, create a new one or reopen this! 

Thank you!
