### ISSUE TITLE
running with -P 1 seems not to work well 

### ISSUE THREAD

**Issue by shiwanyin** [AstraZeneca-NGS/VarDictJava#304]
Hi,
   thanks for the effort on this tools. i use vardict(VarDict-1.6.0.jar) to call somatic variants on amplicon DNA sequence. when i use -P 1 parameter , i found that the mutation chr17_7577507_T_G( mean variants position is over than 1 but within 5 ) was not called while i called it use illumina software pisces, and we believe the mutation is true. 
the follwning picture is the parameters i used.
![image](https://user-images.githubusercontent.com/35325642/84470571-34517380-acb6-11ea-9416-f7bf01892cf5.png)

**Comment by PolinaBevad** [comment]
Hi @shiwanyin ,
This variant can be filtered by other variant filtering, i.e. quality, frequency, etc. All variant filters are described there: https://github.com/AstraZeneca-NGS/VarDictJava#variant-filtering
So can you run this region with `-p` to see if other variant parameters are met for the conditions on thresholds? If they fit the thresholds, can you provide the BAM file part where you found this?

**Comment by shiwanyin** [comment]
HI,
 i am so sorry to answer so late and thanks for your reply so quickly.

 I understand your meaning. the variant quanlity is OK, and the mutation frequency is 42.6%, everything looks well.

the bam file : https://github.com/shiwanyin/data, bed interval : chr17 7577392 7577511

**Comment by PolinaBevad** [comment]
Hi @shiwanyin,

Thank you for sharing data! 

I see that this variant have a small QRATIO - ratio of high to low quality base calls in reads (https://github.com/AstraZeneca-NGS/VarDictJava#variant-filtering, p.7).

By default we must have one and a half times more high quality bases than low quality bases. 
For this variant the counts are mostly the same (QRATIO=1.025) that's why it was filtered out. 
This threshold can be changed by `-o` option, but I think it is better to add option `-q 22` (that determine threshold for base qualities, default is 22.5) - you have a lot of reads with base_quality=22, so it must help.

**Comment by shiwanyin** [comment]
Hi @PolinaBevad ,
     thanks for your help and your advice is extremely useful .my problem is solved now.
