### ISSUE TITLE
Q) --deldupvar option

### ISSUE THREAD

**Issue by dauss75** [AstraZeneca-NGS/VarDictJava#309]
Hello,

We use UMI to deduplicate the read sequences. Just realizing that by adding "--deldupvar", vardict discards the reads based on the read start position. Seems like I should not use --deldupvar as the dedup is already done by UMI. Any thoughts?

Thank you,
Segun

**Comment by PolinaBevad** [comment]
Hi Segun,

This option is related to duplicated variants but not reads, so it is a different situation. We add this as VarDict works separately on each region from BED file. It means that in case of SV candidates (frequently they can start/end outside the region) which weren't recognized as SV but long indels, there may be duplicate variants before the start of the region. 

So this duplication is not due to duplicate reads but some VarDict specific processing of SVs. You can continue to use it if you don't want to see long indels outside the region!

**Comment by dauss75** [comment]
Thanks Polina for the notes.
I will close this.
