### ISSUE TITLE
Last position of Complex variant shows as SNV

### ISSUE THREAD

**Issue by arturotorreso** [AstraZeneca-NGS/VarDictJava#340]
A few consecutive SNVs have been merged into a complex variant, but the last nucleotide shows up again as an independent SNV. The complex variant itself fails the filters, although the SNV passes them. Is this behavior expected?

```
Chromosome     399     .       ATCT    CATC    71      pSTD    SAMPLE=sample1;TYPE=Complex;DP=8667;VD=4;AF=0.0005;BIAS=2:2;REFBIAS=6599:2063;VARBIAS=1:3;PMEAN=10;PSTD=0;QUAL=35.5;QSTD=1;SBF=0.04447;ODDRATIO=9.59164;MQ=60;SN=8;HIAF=0.0005;ADJAF=0;SHIFT3=0;MSI=1;MSILEN=1;NM=0;HICNT=4;HICOV=8488;LSEQ=CTTATCAGAGGCACGTCAAC;RSEQ=TAAAGATGGCACTTGTGGCT;DUPRATE=0;SPLITREAD=0;SPANPAIR=0    GT:DP:VD:AD:AF:RD:ALD   0/1:8667:4:8662,4:0.0005:6599,2063:1,3
Chromosome     402     .       T       C       134     PASS    SAMPLE=sample1;TYPE=SNV;DP=8707;VD=15;AF=0.0017;BIAS=2:2;REFBIAS=6694:1980;VARBIAS=11:4;PMEAN=8.5;PSTD=1;QUAL=34.4;QSTD=1;SBF=0.75835;ODDRATIO=1.22936;MQ=60;SN=30;HIAF=0.0018;ADJAF=0.0001;SHIFT3=1;MSI=2;MSILEN=1;NM=1.1;HICNT=15;HICOV=8386;LSEQ=ATCAGAGGCACGTCAACATC;RSEQ=TAAAGATGGCACTTGTGGCT;DUPRATE=0;SPLITREAD=0;SPANPAIR=0    GT:DP:VD:AD:AF:RD:ALD   0/1:8707:15:8674,15:0.0017:6694,1980:11,4
```

I usually decompose these sort of complex variants into individual records, and then remove duplicates (keeping the PASS one if any), but I thought it would be worth reporting this in case it's non expected.

**Comment by worker000000** [comment]
the 2 variants output at the same time?

**Comment by arturotorreso** [comment]
Yes, it happens quite often! I have to say that so far it occurs in variants with little support that will most likely be filtered at later stages.

**Comment by PolinaBevad** [comment]
Hi @arturotorreso,

Yes, sometimes we do not merge fully complex variants with SNP if there is not enough quality, so SNP will remain there as separate variant as well. If they start on the same position, then one with the higher AF will be printed by default on next step, but in this case SNP is at the end, so we do not filter out complex due to this reason (pSTD is another thing). 
So it is not a bug, we do not want to lose information about this SNP, so VarDict will keep it.

**Comment by arturotorreso** [comment]
Got it, makes sense!
