### ISSUE TITLE
Configuring amplicon mode

### ISSUE THREAD

**Issue by drmjc** [AstraZeneca-NGS/VarDictJava#49]
Hi,
I'm struggling to get my head around the combination of settings required for running in amplicon mode. I've worked out that using `-a int:float`, a regions file needs to be a BED8, and must be tumour-only. 

Based on a small custom BAM file around PTEN gene, i've tried a number of regions file, including whole chrom, whole gene, known exons, actual amplicon locations (this is from a HaloPlex design). Each time I need to use a large int value in the -a to see any variants.
If I run the whole chrom or whole gene, and -a 1000000:0.95, then i find 44 variants. 
If I make a new BED file that spans 40bp around each of these known variants, and use -a 10:0.95, or -a 30:0.95, I find none of them.

So at this stage the only way i can see variants is to use an absurdly large int value for `-a`. From the documentation "...if the edges are less than int bp to the amplicon": does this mean the variant must be within 10bp of the end of the amplicon by default?

![image](https://cloud.githubusercontent.com/assets/591923/17733377/9b34887e-64b9-11e6-8f38-ef76b8bd187a.png)

This image shows the exons, the haloplex amplicons, the variants, and the bed file surrounding these variants.

any help would be greatly appreciated

cheers,
Mark

**Comment by mjafin** [comment]
Hi Mark,
Thanks for your interest in trying out VarDict. The amplicon aware mode in VarDict is specifically meant for PCR amplicon panels that have fixed start and end points for the reads. Such panels include e.g. the Qiagen GeneRead panels and the proper bed files are provided by Qiagen. Here are two example lines from their panel:
```
chr1    115247094       115247253       NRAS    0       .       115247117       115247232
chr1    115247202       115247341       NRAS    0       .       115247224       115247323
```
In these regions, we know that all reads for the first amplicon start at `115247094` (in terms of 0-based coordinates) or `115247253` (the end of the amplicon). The primers are between `[115247094 115247117]` and `[115247232 115247253]` for the first amplicon and the actual DNA fragment is between `[115247117 115247232]`. The same applies to the (overlapping) amplicon 2. 

VarDict uses this information of primer vs. DNA fragment of overlapping amplicons to shun using the primers in reads. 

I'm not too familiar with Haloplex, but you would need to get a similar bed file that lists the regions in the above format (columns 7,8 are a subset of 2,3). Otherwise you'll get misleading/incorrect results unfortunately. Apologies if the above description isn't clear enough, happy to elaborate more.

**Comment by drmjc** [comment]
Hi Mjafin,
Thanks for the quick response. In the image above, in the middle Amplicons_PTEN track we've tried to emulate what you've just described, by trimming the 7th & 8th columns to be a bit (maybe 15-20bp) shorter than the amplicon. Haloplex has lots of overlapping amplicons, thus they're stacking up on top of each other. Can you please explain the intent of the `-a int` and why this works if i set it to a huge value?
cheers,
Mark

**Comment by mjafin** [comment]
Hi Mark,
Looking at the image, there seem to be multiple overlapping amplicons that are almost identical (same starting point but slightly differing end). I suspect VarDict might struggle to assign the reads to the correct amplicons. If you look at the Qiagen amplicons, they overlap fairly little so assignment is easier. Not sure if this the problem with your data but could well be. 

Cheers,
Miika

**Comment by drmjc** [comment]
Hi Miika,
ok, fair enough, i did wonder if overlapping amplicons was going to be a problem. Even if I fake one amplicon per exon, with 7th & 8th columns shorter, i'm not having much luck. 

Is the intent of `-a` to filter out reads that don't start close enough to each end, or to filter out variants that are too far from each end? 

My poor performance during testing with default `-a 10:0.95` could be because i'm testing using reads from capture data, not amplicon, thus if `-a` filters out all reads that don't start within 10bp of the expected amplicon start, then that would explain it.

cheers,
Mark

**Comment by mjafin** [comment]
I'm 99% sure the intent of `-a` is to filter reads (too far from each end) but @zhongwulai would know for certain (he's off on holiday I think so may not get a notification). 

The amplicon mode is not suitable for hybrid or other types of capture where there is any wiggle in the starting points vs. the amplicons in the bed file; it's strictly for PCR amplicon or similar data. 

As an aside, I've been told that HaloPlex is quite poor for FFPE tissue samples.

**Comment by drmjc** [comment]
Thanks Miika, that's making sense now.

**Comment by mjafin** [comment]
Cheers Mark I'll close the ticket for now, let us know if you need any further help or clarification for using VarDict.

**Comment by drmjc** [comment]
no probs, thanks again.
