### ISSUE TITLE
-th thread argument given in github documentation, but not implemented?

### ISSUE THREAD

**Issue by Tabea-K** [AstraZeneca-NGS/VarDictJava#59]
Hi there,
when I tried to use the `-th [threads]` option that is described in the Readme file, VarDictJava quit with this error message:

`Can't open 2: No such file or directory at ../VarDictJava/VarDict/vardict line 93.`

Then, I checked, whether the `-th` option is described in the help (`-h`), and it apparently isn't featured there.

Hence my question: is there an option to set the number of threads to use?

**Comment by mjafin** [comment]
Hi @Tabea-K, thanks for trying VarDict and sorry about the problems. I take it without `-th` it's working OK? If so, maybe @ZLyanov and his team could take a look at this.

**Comment by Tabea-K** [comment]
Yes, it's working fine, when I don't use the option `-th` in the way I used it. I have to specify, that I tried it with a parameter of 2, i.e. `-th 2`. When I leave the parameter 2, and just specify `-th`, VarDict runs without any problems.

**Comment by ZLyanov** [comment]
@Tabea-K We'll check it right now

**Comment by ZLyanov** [comment]
@Tabea-K it seems that you launched the perl version instead of java. Look at the example template from the README, please:  

<path_to_vardict_folder>/build/install/VarDict/bin/VarDict -G /path/to/hg19.fa -f $AF_THR -N sample_name -b /path/to/my.bam -z -c 1 -S 2 -E 3 -g 4 /path/to/my.bed | VarDict/teststrandbias.R | VarDict/var2vcf_valid.pl -N sample_name -E -f $AF_THR
