### ISSUE TITLE
java.lang.StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by ltfang-bina** [AstraZeneca-NGS/VarDictJava#7]
I have seen the following exit message on error:

Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
at java.lang.String.charAt(String.java:658)
at com.astrazeneca.vardict.VarDict.modifyCigar(VarDict.java:6065)
at com.astrazeneca.vardict.VarDict.parseSAM(VarDict.java:1529)
at com.astrazeneca.vardict.VarDict.toVars(VarDict.java:2515)
at com.astrazeneca.vardict.VarDict.somaticNotParallel(VarDict.java:356)
at com.astrazeneca.vardict.VarDict.nonAmpVardict(VarDict.java:251)
at com.astrazeneca.vardict.VarDict.start(VarDict.java:67)
at com.astrazeneca.vardict.Main.run(Main.java:137)
at com.astrazeneca.vardict.Main.main(Main.java:24)

I have two small BAM files of 1.5 MB each in size that can reproduce this error.

Command used were:
VarDictJava/build/install/VarDict/bin/VarDict -G human_g1k_v37_decoy.fasta -f 0.01 -h -b 'tumor.errored.bam|normal.errored.bam' -C -c 1 -S 2 -E 3 -g 4 errored.5kbps.bed 2> errored.msg > errored.var

Is there a way I can get the BAM files to you guys?

Thanks.

**Comment by ltfang-bina** [comment]
I've uploaded the files onto the Google Drive:
https://drive.google.com/folderview?id=0B9pfRlnkG-Z7flIwMExkSjVWRllybmgzUHcxWGJLWmRsR0hzckhmZUJjMk9kX1lMUmZBUVk&usp=sharing

The data a tiny region from the DREAM Challenge Stage 3 data (public data).

**Comment by jabbarish** [comment]
thank you

**Comment by zhongwulai** [comment]
Hi Li Tai,

I seriously think there's a bug in your alignment process.  The problem is caused again by an illegal alignment with CIGAR 66S2M19I14S, which indicates there're only 2bp reference matches in the alignment.  19bp insertion followed by 14bp soft clipping doesn't make sense.  When you look at the alignment, neither of 2bp matches to reference.  I haven't seen BWA making such alignment in my experience, so wondering whether it's any post-processing or parallelization?  VarDict's algorithm tries to modify CIGAR so that it can do effective local realignment, but it assumes there's a least one bp match to reference to break out the loop (should be a valid assumption for a valid alignment).  If no match was found, this error happened.  Perl's version should produce warning messages with unknown consequences, while Java's version might just throw an exception you saw.

-Zhongwu

**Comment by ltfang-bina** [comment]
Hi Zhongwu,

Thanks for digging into this.

Are you specifically talking about this issue I posted on github here:
https://github.com/AstraZeneca-NGS/VarDictJava/issues/11
In this case, the BAM files were downloaded directly from CGHUB, and
according to the BAM header it was by BWA 0.5.9 and GATK IndelRealignment.
We did not create these BAM files.

If you were talking about the previous set of data, then let me try to
re-produce this issue on the cluster off the box, and see if the problem is
caused by the software we use, or caused by our parallelization process on
the Box.
I know that AZ just discovered a bug with regard to mark duplicates that
was caused by parallelization. We fixed that, although I'm not sure if that
fix has made it to the Box yet.

Thanks again.


*-- Li Tai Fang, PhD  *//  Bioinformatics Scientist, Bina Technologies,
part of Roche Sequencing

E. ltfang@bina.com   //   Tel. +1.650.779.4564

*Learn More*  //  video <http://www.bina.com/product.html>  //  news
<http://www.bina.com/press-coverage.html>  //  posters
<http://info.bina.com/posters>  //  science
<http://www.bina.com/science.html>  //  platform
<http://www.bina.com/platform.html>

**Comment by dh10** [comment]
The BAMs producing this error on our end are realigned with Abra (https://github.com/mozack/abra) after BWA MEM ...

**Comment by rhshah** [comment]
Has this issue been resolved, i get similar error:
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.charAt(String.java:658)
	at com.astrazeneca.vardict.VarDict.parseSAM(VarDict.java:1927)
	at com.astrazeneca.vardict.VarDict.toVars(VarDict.java:2537)
	at com.astrazeneca.vardict.VarDict.vardictNotParallel(VarDict.java:304)
	at com.astrazeneca.vardict.VarDict.nonAmpVardict(VarDict.java:257)
	at com.astrazeneca.vardict.VarDict.start(VarDict.java:68)
	at com.astrazeneca.vardict.Main.run(Main.java:134)
	at com.astrazeneca.vardict.Main.main(Main.java:25)

Also our bam files are realigned using ABRA.

**Comment by mjafin** [comment]
Hi @rhshah, Based on the above discussion it sounds like these may be caused by improper alignments/CIGAR strings. If you can identify the exact region and reads that cause this then you could take a look how the (re)alignments look like (maybe your problem is caused by something else). Our aim is to support bwa alignments and utilise VarDict's built-in realignment; it will be very difficult to foresee and account for inmproper CIGARs that arise from external realigners.

**Comment by rhshah** [comment]
Hi @mjafin  thanks for you reply i appreciate, but I ran the same bam file for the perl version and it ran without any issue, though looks like it took lot of time to finish.

I am not sure if I would be able to pin point where its happening but its always stops after this co-ordinate => 1:156452350, as VarDict does not output the any other information its hard to tell where exactly this might be happening .

**Comment by mjafin** [comment]
Hi @rhshah, we've seen this quite often that the perl version doesn't die but Java does as perl isn't as bothered about "illegal" operations (like nonexisting variables etc.) If you could identify the exact region and slice your bam file in that region for us we could maybe take a look.

**Comment by rhshah** [comment]
Thanks @mjafin, I have pinpointed the region where this is happening its in a gene called SDHA, attaching the file here.
[VardicTestBamFile.zip](https://github.com/AstraZeneca-NGS/VarDictJava/files/68979/VardicTestBamFile.zip)

**Comment by mjafin** [comment]
Thanks @rhshah. I'm off until January but was wondering if @jabbarish or @zhongwulai were still in office? If not, bear with us

**Comment by rhshah** [comment]
Sure no issues, will be great to know if it is fixable.

**Comment by jabbarish** [comment]
Hi!  We will try to find out what can be done to fix it.  I'll write back on thursday of friday.

**Comment by rhshah** [comment]
Thanks @jabbarish

**Comment by jabbarish** [comment]
The issue appears when a CIGAR filed of a read starts with deletion, for example “1D100M”.
 
According to the current algorithm, the quality value for deletion is taken from the previous position: q1 = queryQuality.charAt(n-1), where n  is the index of the current position. If deletion is in the first position, we have n = 0 and thus we are trying to get the ‘-1’ position of quality string. In Java it causes java.lang.StringIndexOutOfBoundsException, in Perl the first from the end quality char is selected, but it does not seem to be right – the quality of deletion is not connected with the quality of the last position.
In order to solve this problem we can set some default quality for such situations, and use it when we meet deletion in the first position/positions.

**Comment by rhshah** [comment]
Thanks @jabbarish for looking into this, will appreciate if you lets us know when you update the codebase.

**Comment by mjafin** [comment]
I think we need @zhongwulai to make a design decision here as this is a problem in both code bases.

**Comment by chapmanb** [comment]
@mjafin, @zhongwulai @jabbarish -- folks are running into this bug and I wonder if it's possible to get a fix in place and roll a new release (chapmanb/bcbio-nextgen#1225). My suggestion would be to pick the quality value of the next base after the deletion, or use a default quality like 30. Since the current behavior of wrapping around the sequence isn't correct I don't think we're entering very dangerous territory by pushing something reasonable.

**Comment by mjafin** [comment]
@jabbarish would you be able to implement this if @zhongwulai has no objections? Zhongwu you may want to implement something similar in Perl just to keep things in sync.

**Comment by jabbarish** [comment]
@mjafin sure, we are ready.  Shall we do it now or  wait for @zhongwulai to confirm the prosposed aproach?

**Comment by mjafin** [comment]
Zhongwu seems to be off until Weds, let's give him a few days to check this thread and then move forward with the proposed fix.

**Comment by zhongwulai** [comment]
OK, I think this is more aligner bug.  Many of clauses in VarDict are dedicated to fix such bugs.  The better fix is to fix the CIGAR.  I would add following before line 685 in Perl version:

            $a[5] =~ s/^\d+D//;
            $a[5] =~ s/\dD$//;
            $a[5] =~ s/^(\d+)I/\1S/ );
            $a[5] =~ s/(\d+)I$/\1S/ );

-Zhongwu

**Comment by mjafin** [comment]
@jabbarish Zhongwu pushed this fix into Github, maybe you could follow with the Java version?

**Comment by zhongwulai** [comment]
I've push an updated Perl version into github, it also fixes issue #26, where an indel with microhomology can sometimes be missed in pair mode.

**Comment by mjafin** [comment]
Would be cool to get these both into the Java version and push out a new release.

**Comment by jabbarish** [comment]
@mjafin We are going to make new release with the fixes by Monday.
