### ISSUE TITLE
-O flag in Java version vs. -Q flag in Perl version

### ISSUE THREAD

**Issue by ltfang-bina** [AstraZeneca-NGS/VarDictJava#8]
I noticed that in the Perl version, -Q enforces a minimum mapping quality, but in Java version it's -O. 
I'm just wondering if it's intentional, or the tail in Q was accidentally lost to become an O.

**Comment by jabbarish** [comment]
Hi!  Perl version contains both.  So does Java version too.
-Q INT
       If set, reads with mapping quality less than INT will be filtered and ignored
 -O MapQ
       The reads should have at least mean MapQ to be considered a valid variant. Default: no filtering

But you are right in the fact that Java version doesn't count -Q,  simply ignores it. This is due to accidentally omitted code portion to parse -Q option.  The code processing it exists though.
We will fix it in the next release.
