### ISSUE TITLE
Variant not called by VarDict

### ISSUE THREAD

**Issue by wendymclee3** [AstraZeneca-NGS/VarDictJava#81]
I am looking at a variant that is not being called in some samples, but it's not apparent why it is not called when all samples have 500+ read coverage at the locus. The call is not being made by VarDict even before running teststrandbias.R or var2vcf_valid.pl. I am running a version of VarDictJava from March 2017. I am attaching two bam files here, 20170601-D2NGC-S1.PrimaryAlignment.bam is the one that didn't get called at chr5:178690725 while 20170601-D2NGC-S4.PrimaryAlignment.bam got the call. Pileup results shows that both sample have A>G about 0.74 MAF. 
[bamFiles.zip](https://github.com/AstraZeneca-NGS/VarDictJava/files/1049028/bamFiles.zip)

**Comment by mjafin** [comment]
Hi @wendymclee3, do you think it's related to this issue https://github.com/AstraZeneca-NGS/VarDictJava/issues/62 ?

@ZLyanov do your team have time to take a look at this at some point?

**Comment by ekazachkova** [comment]
@wendymclee3 we've run VarDictJava on your data with the following command:
` 
-G hg19.fa -b your.bam -c 1 -S 2 -E 3 -g 4 -R chr5:178690725-178690726
`
The variation was detected:
```
20170601-D2NGC-S1.PrimaryAlignment chr5 chr5 178690725 178690725 G A 595 445 5 143 13 432 G/A 0.7479 1;1 30.9 1 38.2 1 60.0 73.167 0.7530 0 0 4.000 2 1.3 439 583 CCCTTGTCCCAAACGTGTGT TGCACAGGCACACGAAAGAA chr5:178690725-178690726 SNV
```
Could you share VarDict command that you've used?

**Comment by wendymclee3** [comment]
${Vardict}/VarDict -G ${Reference} -N tumor -b ${BamFile} -z 1 -c 1 -S 2 -E 3 -g 4 -f 0 -F 0x700 -q 30 -th 1 ${BedFile}

**Comment by ekazachkova** [comment]
@wendymclee3 thanks so much for the information.
We've used your set of parameters and still got the variation reported. 
One thing you could try is changing `-z` option to `0`: it makes an impact if the region with variation starts right at the specified position (e.g. in your situation if the region starts with 178690725 position variation won't be reported).
Please let us know whether it works for you.

**Comment by wendymclee3** [comment]
The variant was called only if -R chr5:178690725-178690726 is used, but when using a bed file that contain the locus, that variant was only called in a subset of the samples (all samples are prepared the same way and sequenced together). Here is the IGV screenshot (20170601-D2NGC-S1.PrimaryAlignment.bam didn't get the call, but 20170601-D2NGC-S4.PrimaryAlignment.bam got the call). I am using the latest version of VarDict freshly pulled from the repo.
<img width="1415" alt="screen shot 2017-06-06 at 11 02 46 am" src="https://user-images.githubusercontent.com/18375756/26844416-30f9086a-4aa8-11e7-862c-3b855dd6fb0d.png">

**Comment by wendymclee3** [comment]
The variant was called only if -R chr5:178690725-178690726 is used, but when using a bed file that contain the locus, that variant was only called in a subset of the samples (all samples are prepared the same way and sequenced together). Here is the IGV screenshot (20170601-D2NGC-S1.PrimaryAlignment.bam didn't get the call, but 20170601-D2NGC-S4.PrimaryAlignment.bam got the call). I am using the latest version of VarDict freshly pulled from the repo.
<img width="1413" alt="screen shot 2017-06-06 at 11 09 06 am" src="https://user-images.githubusercontent.com/18375756/26844527-9623c0ae-4aa8-11e7-9692-8da705ed4ef4.png">

**Comment by ekazachkova** [comment]
@wendymclee3 thanks for the information. We've expanded the region to `chr5:178690706-178690800` but still can't reproduce your situation. Could you share the BED file that you've used?

**Comment by ekazachkova** [comment]
@wendymclee3 thanks again for the information. Unfortunately, we still can't reproduce this bug. We've run the latest version of VarDictJava (https://github.com/AstraZeneca-NGS/VarDictJava/releases/tag/v1.5.1) on your data [[bamFiles.tar.gz](https://github.com/AstraZeneca-NGS/VarDictJava/files/1088787/bamFiles.tar.gz)] using the following command:
```
<path_to_vardict_folder>/build/install/VarDict/bin/VarDict -b 20170601-D2NGC-S1.PrimaryAlignment.bam -G hg19.fa -N tumor -z 1 -c 1 -S 2 -E 3 -g 4 -f 0 -F 0x700 -q 30 -th 1 Targets.bed
```
We've got these outputs for both BAM files:

[20170601-D2NGC-S1.PrimaryAlignment.out.txt](https://github.com/AstraZeneca-NGS/VarDictJava/files/1088790/20170601-D2NGC-S1.PrimaryAlignment.out.txt)
[20170601-D2NGC-S4.PrimaryAlignment.out.txt](https://github.com/AstraZeneca-NGS/VarDictJava/files/1088792/20170601-D2NGC-S4.PrimaryAlignment.out.txt)

Could you please run VarDict on your BAM and BED files that we've attached with the command we've provided and compare your outputs with our?

**Comment by PolinaBevad** [comment]
@wendymclee3, hello!
I will close the issue because we could not reproduce the problem and there was no response to the last questions.
If this issue is still relevant to you, please, reopen it! Thanks.

**Comment by ALFLAG** [comment]
Hi @PolinaBevad 
I send a new message on this issue because I'm facing the same problem.
One variant is not called, despite the fact that it is the most present base in the alignment.
I sent you an archive with data, command line, and results files I have on this problem.
[vardict_issue_files.tar.gz](https://github.com/AstraZeneca-NGS/VarDictJava/files/4044925/vardict_issue_files.tar.gz)

Briefly, in position 7160, when NOT using the -p option (I always do that) the variant is not called (see vardict_result file). When adding the -p option (I read the links in discussion above), the variant is called, but the PASS flag is not set (see vardict_results_with_pileup_option).
Moreover, when adding the -p option, why do I have pileup results for position where there is no data (the bamfile start at position 6902 and the vardict_results_with_pileup_option file give me results before the starting position). Why is that ?
And therefore, in which conditions should we used the p option?


Thanks a lot.

**Comment by PolinaBevad** [comment]
Hi @ALFLAG,

`-p` option helps to see what parameters the filtered out variant has. Also, it can be used for WGS calling if you want to create gVCF file that will contain REF==ALT. That's why it also outputs some positions outside the region (some possible SVs sites, for example). The `-p` option doesn't apply filters on quality, frequency, ratios, etc, so you have some kind of a raw result. 

The variant on position 7160 has a small mean base quality (14.9) and qratio (0.83). If you set `-q` to 5 (instead of `-Q` which is for mapping quality), then the variant will appear, because the base quality and qratio would be higher then thresholds. Qratio is recalculated when you change `-q` threshold because reads that were considered bad before, will be "good" now.  

I hope it helps you.

**Comment by ALFLAG** [comment]
this definitly helps, thank you @PolinaBevad 

Alex
