### ISSUE TITLE
Variant classified as StrongSomatic, but clearly germline

### ISSUE THREAD

**Issue by ATpoint** [AstraZeneca-NGS/VarDictJava#83]
Hello,

I am using VDJ on a matched tumor-normal WGS sample, with the command below. Sometimes I notice that variants classified as StrongSomatic in the VCF show the same mutation at similar frequency in the matched control (manual inspection on IGV browser of the used BAMs). It would be great if you could look into it.

The command was the followjng:

`VarDictJava -G $HG38FA -f 0.1 -N $SAMPLENAME -b "${BAM_TUMOR}|${BAM_NORMAL}" -z 0 -F 0x500 -q 25 -r 3 -c 1 -S 2 -E 3 -g 4 -Q 1 -O 1 -th $THREADS -t $BEDFILE | \
$TestSomatic | $Var2VcfPaired -N "${SAMPLENAME}_tumor|${SAMPLENAME}_normal" -f 0.1 -S -A > $OUTFILE`

[Here](https://uni-muenster.sciebo.de/index.php/s/mW5GhjmeMI0IQaF) are two small BAM files (tumor and normal) that cover one of these regions.

Running it on a bedfile with "chr16:46389000-46390000" and greping for "StrongSomatic" should give this result:

chr16	46389601	.	C	T	365	PASS	STATUS=StrongSomatic;SAMPLE=test_tumor;TYPE=SNV;SHIFT3=0;MSI=2.000;MSILEN=1;SSF=0;SOR=Inf;LSEQ=AATGGAATCTAATGGAATCA;RSEQ=CATCGAATGAAATTGAGTGG	GT:DP:VD:ALD:RD:AD:AF:BIAS:PMEAN:PSTD:QUAL:QSTD:SBF:ODDRATIO:MQ:SN:HIAF:ADJAF:N	1/1:3930:3479:1980,1499:119,115:234,3479:0.8852:2,2:16.4:1:31.1:1:0.07647:1.28:21.8:4.071:0.9433:0:4.7	0/0:3611:0:0,0:86,79:165,0:0:2,0:18.6:1:33:1:1:0:35.1:5.6:0.9524:0:4.4

But [this](https://uni-muenster.sciebo.de/index.php/s/75BD36jl8n8ppwR) is what I see on the IGV. Clearly, the AF does not match with the VCF. Can you help me with this?

**Comment by zhongwulai** [comment]
@ATpoint, thank you for your feedback and sending the example data.  After some digging, I think I found the root cause.  First of all, this region is close to centromere and has very low complexity.  In WGS of NA12878 (~50x), the peak coverage is 70,000.  That means any variant called in this region is not reliable as many similar alleles are piled up (see coverage image below or attached, where it shows the mappability and coverage NA12878 and your normal sample).  
![image](https://user-images.githubusercontent.com/8194727/28539786-ebf081b8-7080-11e7-96bf-d1868a0138b8.png)
That said, it appears that there's potentially one allele with 49bp deletion and 1bp insertion of (G) between 46389593 and 46389642, which is more prominent in normal.  The allele can be forced to have ungapped alignment, and will produce the SNV you indicated.  VarDict's realignment engine of this allele in normal sample assigned this SNV to the deletion, while tumor sample kept the SNV, resulting in normal sample seemingly lacking the SNV, thus the StrongSomatic call.  I'm a bit reluctant to modify current realignment algorithm as this rare exception typically showed up in ultra-deep, low complexity region.

I would recommend you to produce a bed file of low complexity regions and always extract those regions in WGS analysis.  This typically removes many false positives and will speed up VarDict tremendously.  

Thanks again,
Best,
Zhongwu

**Comment by ATpoint** [comment]
Hi Zhongwu, thank you very much for the detailed answer. Concerning the low complexity regions you mentioned, do you know if these show significant overlaps with the commonly used [ENCODE blacklists](https://sites.google.com/site/anshulkundaje/projects/blacklists)? If not, how should I create them? I think the most straight-forward way would be to take some commonly used WGS datasets like NA12878 and blacklist all regions whose coverage exceeds the, lets say, 99th percentile? 

best,
Alex

**Comment by ATpoint** [comment]
Thank you very much for the detailed answer. For the future, I will probably exclude all variants with a depth more than 2-3x the mean coverage.
