### ISSUE TITLE
Unclear documentation re reqs for release zip/tar

### ISSUE THREAD

**Issue by datakid** [AstraZeneca-NGS/VarDictJava#84]
I am installing VarDictJava in a multiuser cluster environment, using environment modules to control.

The "Getting the Source Code" Documentation suggests that Perl is a req. 

The Releases page offers a tar/zip download that only contains .jar files.

If I am using the release zips - are they jar only? Do I need to account for samtools or perl in my environment set up?

In particular this line

> Note that the original VardDict project is placed in this repository as a submodule and its contents can be found in the sub-directory VarDict in VarDictJava working folder.

Does that mean the releases zip should have a VarDict directory along with bin and lib?

**Comment by datakid** [comment]
I guess I'm confused as to whether VarDictJava is a complete drop in replacement (as the "releases" zip/tar would indicate) or if the VarDict-<version>/VarDict directory (as per the getting source/compile recommends) is actually an installation requirement.

I think the docs need an Installation section that addresses what is needed after (the end of compilation section|unzip the release). Is it enough to have the bin in the env's PATH? Should I explicitly add the lib to the LD_LIBRARY_PATH or LIB envvar?

Or do I need to grab a copy of the last VarDict (perl) and stick that <somewhere>, and add that to the PATH?

**Comment by datakid** [comment]
Ah! The first example

> <path_to_vardict_folder>/build/install/VarDict/bin/VarDict -G /path/to/hg19.fa -f $AF_THR -N sample_name -b /path/to/my.bam -z -c 1 -S 2 -E 3 -g 4 /path/to/my.bed | VarDict/teststrandbias.R | VarDict/var2vcf_valid.pl -N sample_name -E -f $AF_THR

Would indicate that yes, *as well as* the bin and lib, a clone of the perl version of VarDict is required at the same root?

**Comment by datakid** [comment]
I guess the next question is - given that the perl version of VarDict is still required for some functions - does samtools still need to be on the PATH as well?

**Comment by mjafin** [comment]
Hi @datakid, thanks for your interest in VarDict and sorry about the confusion in the documentation. 
VarDictJava is a drop-in replacement of `vardict.pl` only and the following piped R (`teststrandbias.R` / `testsomatic.R`) and perl (`var2vcf_valid.pl` / `var2vcf_paired.pl`) scripts are still required to be available. So yes, you will need to have Rscript and perl available in the environment.

Samtools is not required if you run VarDictJava instead of `vardict.pl` as it uses htsjdk to reduce forking etc. 

As an alternative way of running the whole VarDict pipeline may I suggest you take a look at bcbio (https://github.com/chapmanb/bcbio-nextgen) as a holistic alternative?

**Comment by PolinaBevad** [comment]
@datakid, we update documentation in PR #133: added information about distribution package structure and third-party libraries. 
I will close this issue. You can reopen it if needed.
